# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)

#### Import data set.

Import data set `Pokemon` from [kaggle](https://www.kaggle.com/abcsds/pokemon/) . Read the data into a dataframe called `pokemon`.

In [3]:
Pokemon_Path = 'Pokemon.csv'

Pokemon = pd.read_csv(Pokemon_Path)

#### Print first 10 rows of `pokemon`.

In [5]:
# your code here
Pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [8]:
# your code here
#column_a_values = df['a'].values
#column_b_values = df['b'].values

values_Type_1, values_Type_2 = Pokemon['Type 1'].values, Pokemon['Type 2'].values
values_Type_1, values_Type_2

(array(['Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Fire',
        'Fire', 'Water', 'Water', 'Water', 'Water', 'Bug', 'Bug', 'Bug',
        'Bug', 'Bug', 'Bug', 'Bug', 'Normal', 'Normal', 'Normal', 'Normal',
        'Normal', 'Normal', 'Normal', 'Normal', 'Poison', 'Poison',
        'Electric', 'Electric', 'Ground', 'Ground', 'Poison', 'Poison',
        'Poison', 'Poison', 'Poison', 'Poison', 'Fairy', 'Fairy', 'Fire',
        'Fire', 'Normal', 'Normal', 'Poison', 'Poison', 'Grass', 'Grass',
        'Grass', 'Bug', 'Bug', 'Bug', 'Bug', 'Ground', 'Ground', 'Normal',
        'Normal', 'Water', 'Water', 'Fighting', 'Fighting', 'Fire', 'Fire',
        'Water', 'Water', 'Water', 'Psychic', 'Psychic', 'Psychic',
        'Psychic', 'Fighting', 'Fighting', 'Fighting', 'Grass', 'Grass',
        'Grass', 'Water', 'Water', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire',
        'Water', 'Water', 'Water', 'Electric', 'Electric', 'Normal',
        'Normal', 'Normal', 'Water', 'Water', 'Poison', 'Poison', 'Water',
        'Water', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Rock', 'Psychic',
        'Psychic', 'Water', 'Water', 'Electric', 'Electric', 'Grass',
        'Grass', 'Ground', 'Ground', 'Fighting', 'Fighting', 'Normal',
        'Poison', 'Poison', 'Ground', 'Ground', 'Normal', 'Grass',
        'Normal', 'Normal', 'Water', 'Water', 'Water', 'Water', 'Water',
        'Water', 'Psychic', 'Bug', 'Ice', 'Electric', 'Fire', 'Bug', 'Bug',
        'Normal', 'Water', 'Water', 'Water', 'Water', 'Normal', 'Normal',
        'Water', 'Electric', 'Fire', 'Normal', 'Rock', 'Rock', 'Rock',
        'Rock', 'Rock', 'Rock', 'Normal', 'Ice', 'Electric', 'Fire',
        'Dragon', 'Dragon', 'Dragon', 'Psychic', 'Psychic', 'Psychic',
        'Psychic', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire',
        'Water', 'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Normal',
        'Bug', 'Bug', 'Bug', 'Bug', 'Poison', 'Water', 'Water', 'Electric',
        'Fairy', 'Normal', 'Fairy', 'Fairy', 'Psychic', 'Psychic',
        'Electric', 'Electric', 'Electric', 'Electric', 'Grass', 'Water',
        'Water', 'Rock', 'Water', 'Grass', 'Grass', 'Grass', 'Normal',
        'Grass', 'Grass', 'Bug', 'Water', 'Water', 'Psychic', 'Dark',
        'Dark', 'Water', 'Ghost', 'Psychic', 'Psychic', 'Normal', 'Bug',
        'Bug', 'Normal', 'Ground', 'Steel', 'Steel', 'Fairy', 'Fairy',
        'Water', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Dark', 'Normal',
        'Normal', 'Fire', 'Fire', 'Ice', 'Ice', 'Water', 'Water', 'Water',
        'Ice', 'Water', 'Steel', 'Dark', 'Dark', 'Dark', 'Water', 'Ground',
        'Ground', 'Normal', 'Normal', 'Normal', 'Fighting', 'Fighting',
        'Ice', 'Electric', 'Fire', 'Normal', 'Normal', 'Electric', 'Fire',
        'Water', 'Rock', 'Rock', 'Rock', 'Rock', 'Psychic', 'Fire',
        'Psychic', 'Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire',
        'Fire', 'Fire', 'Water', 'Water', 'Water', 'Water', 'Dark', 'Dark',
        'Normal', 'Normal', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Water',
        'Water', 'Water', 'Grass', 'Grass', 'Grass', 'Normal', 'Normal',
        'Water', 'Water', 'Psychic', 'Psychic', 'Psychic', 'Psychic',
        'Bug', 'Bug', 'Grass', 'Grass', 'Normal', 'Normal', 'Normal',
        'Bug', 'Bug', 'Bug', 'Normal', 'Normal', 'Normal', 'Fighting',
        'Fighting', 'Normal', 'Rock', 'Normal', 'Normal', 'Dark', 'Dark',
        'Steel', 'Steel', 'Steel', 'Steel', 'Steel', 'Steel', 'Fighting',
        'Fighting', 'Fighting', 'Electric', 'Electric', 'Electric',
        'Electric', 'Electric', 'Bug', 'Bug', 'Grass', 'Poison', 'Poison',
        'Water', 'Water', 'Water', 'Water', 'Water', 'Fire', 'Fire',
        'Fire', 'Fire', 'Psychic', 'Psychic', 'Normal', 'Ground', 'Ground',
        'Ground', 'Grass', 'Grass', 'Normal', 'Dragon', 'Dragon', 'Normal',
        'Poison', 'Rock', 'Rock', 'Water', 'Water', 'Water', 'Water',
        'Ground', 'Ground', 'Rock', 'Rock', 'Rock', 'Rock', 'Water',
        'Water', 'Normal', 'Normal', 'Ghost', 'Ghost', 'Ghost', 'Ghost',
        'Ghost', 'Grass', 'Psychic', 'Dark', 'Dark', 'Psychic', 'Ice',
        'Ice', 'Ice', 'Ice', 'Ice', 'Ice', 'Water', 'Water', 'Water',
        'Water', 'Water', 'Dragon', 'Dragon', 'Dragon', 'Dragon', 'Steel',
        'Steel', 'Steel', 'Steel', 'Rock', 'Ice', 'Steel', 'Dragon',
        'Dragon', 'Dragon', 'Dragon', 'Water', 'Water', 'Ground', 'Ground',
        'Dragon', 'Dragon', 'Steel', 'Psychic', 'Psychic', 'Psychic',
        'Psychic', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire',
        'Water', 'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Normal',
        'Normal', 'Bug', 'Bug', 'Electric', 'Electric', 'Electric',
        'Grass', 'Grass', 'Rock', 'Rock', 'Rock', 'Rock', 'Bug', 'Bug',
        'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Electric', 'Water', 'Water',
        'Grass', 'Grass', 'Water', 'Water', 'Normal', 'Ghost', 'Ghost',
        'Normal', 'Normal', 'Normal', 'Ghost', 'Dark', 'Normal', 'Normal',
        'Psychic', 'Poison', 'Poison', 'Steel', 'Steel', 'Rock', 'Psychic',
        'Normal', 'Normal', 'Ghost', 'Dragon', 'Dragon', 'Dragon',
        'Dragon', 'Normal', 'Fighting', 'Fighting', 'Fighting', 'Ground',
        'Ground', 'Poison', 'Poison', 'Poison', 'Poison', 'Grass', 'Water',
        'Water', 'Water', 'Grass', 'Grass', 'Grass', 'Dark', 'Electric',
        'Normal', 'Ground', 'Grass', 'Electric', 'Fire', 'Fairy', 'Bug',
        'Grass', 'Ice', 'Ground', 'Ice', 'Normal', 'Psychic', 'Psychic',
        'Rock', 'Ghost', 'Ice', 'Electric', 'Electric', 'Electric',
        'Electric', 'Electric', 'Electric', 'Psychic', 'Psychic',
        'Psychic', 'Steel', 'Water', 'Fire', 'Normal', 'Ghost', 'Ghost',
        'Psychic', 'Water', 'Water', 'Dark', 'Grass', 'Grass', 'Normal',
        'Psychic', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire',
        'Water', 'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Normal',
        'Normal', 'Dark', 'Dark', 'Grass', 'Grass', 'Fire', 'Fire',
        'Water', 'Water', 'Psychic', 'Psychic', 'Normal', 'Normal',
        'Normal', 'Electric', 'Electric', 'Rock', 'Rock', 'Rock',
        'Psychic', 'Psychic', 'Ground', 'Ground', 'Normal', 'Normal',
        'Fighting', 'Fighting', 'Fighting', 'Water', 'Water', 'Water',
        'Fighting', 'Fighting', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug', 'Bug',
        'Grass', 'Grass', 'Grass', 'Grass', 'Water', 'Ground', 'Ground',
        'Ground', 'Fire', 'Fire', 'Fire', 'Grass', 'Bug', 'Bug', 'Dark',
        'Dark', 'Psychic', 'Ghost', 'Ghost', 'Water', 'Water', 'Rock',
        'Rock', 'Poison', 'Poison', 'Dark', 'Dark', 'Normal', 'Normal',
        'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Psychic', 'Psychic',
        'Water', 'Water', 'Ice', 'Ice', 'Ice', 'Normal', 'Normal',
        'Electric', 'Bug', 'Bug', 'Grass', 'Grass', 'Water', 'Water',
        'Water', 'Bug', 'Bug', 'Grass', 'Grass', 'Steel', 'Steel', 'Steel',
        'Electric', 'Electric', 'Electric', 'Psychic', 'Psychic', 'Ghost',
        'Ghost', 'Ghost', 'Dragon', 'Dragon', 'Dragon', 'Ice', 'Ice',
        'Ice', 'Bug', 'Bug', 'Ground', 'Fighting', 'Fighting', 'Dragon',
        'Ground', 'Ground', 'Dark', 'Dark', 'Normal', 'Normal', 'Normal',
        'Dark', 'Dark', 'Fire', 'Bug', 'Dark', 'Dark', 'Dark', 'Bug',
        'Bug', 'Steel', 'Rock', 'Grass', 'Flying', 'Flying', 'Electric',
        'Electric', 'Dragon', 'Dragon', 'Ground', 'Ground', 'Dragon',
        'Dragon', 'Dragon', 'Water', 'Water', 'Normal', 'Normal', 'Bug',
        'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Water',
        'Water', 'Water', 'Normal', 'Normal', 'Normal', 'Fire', 'Fire',
        'Bug', 'Bug', 'Bug', 'Fire', 'Fire', 'Fairy', 'Fairy', 'Fairy',
        'Grass', 'Grass', 'Fighting', 'Fighting', 'Normal', 'Psychic',
        'Psychic', 'Psychic', 'Steel', 'Steel', 'Steel', 'Steel', 'Fairy',
        'Fairy', 'Fairy', 'Fairy', 'Dark', 'Dark', 'Rock', 'Rock',
        'Poison', 'Poison', 'Water', 'Water', 'Electric', 'Electric',
        'Rock', 'Rock', 'Rock', 'Rock', 'Fairy', 'Fighting', 'Electric',
        'Rock', 'Dragon', 'Dragon', 'Dragon', 'Steel', 'Ghost', 'Ghost',
        'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost', 'Ghost',
        'Ghost', 'Ice', 'Ice', 'Flying', 'Flying', 'Fairy', 'Dark',
        'Dragon', 'Rock', 'Rock', 'Psychic', 'Psychic', 'Fire'],
       dtype=object),
 array(['Poison', 'Poison', 'Poison', 'Poison', nan, nan, 'Flying',
        'Dragon', 'Flying', nan, nan, nan, nan, nan, nan, 'Flying',
        'Poison', 'Poison', 'Poison', 'Poison', 'Flying', 'Flying',
        'Flying', 'Flying', nan, nan, 'Flying', 'Flying', nan, nan, nan,
        nan, nan, nan, nan, nan, 'Ground', nan, nan, 'Ground', nan, nan,
        nan, nan, 'Fairy', 'Fairy', 'Flying', 'Flying', 'Poison', 'Poison',
        'Poison', 'Grass', 'Grass', 'Poison', 'Poison', nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, 'Fighting', nan, nan, nan,
        nan, nan, nan, nan, 'Poison', 'Poison', 'Poison', 'Poison',
        'Poison', 'Ground', 'Ground', 'Ground', nan, nan, 'Psychic',
        'Psychic', 'Psychic', 'Steel', 'Steel', 'Flying', 'Flying',
        'Flying', nan, 'Ice', nan, nan, nan, 'Ice', 'Poison', 'Poison',
        'Poison', 'Poison', 'Ground', nan, nan, nan, nan, nan, nan,
        'Psychic', 'Psychic', nan, nan, nan, nan, nan, nan, nan, 'Rock',
        'Rock', nan, nan, nan, nan, nan, nan, nan, nan, nan, 'Psychic',
        'Fairy', 'Flying', 'Psychic', nan, nan, nan, 'Flying', nan, nan,
        'Flying', 'Dark', 'Ice', nan, nan, nan, nan, nan, nan, 'Water',
        'Water', 'Water', 'Water', 'Flying', 'Flying', nan, 'Flying',
        'Flying', 'Flying', nan, nan, 'Flying', nan, 'Fighting', nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 'Flying',
        'Flying', 'Flying', 'Flying', 'Poison', 'Poison', 'Flying',
        'Electric', 'Electric', nan, nan, 'Fairy', nan, 'Flying', 'Flying',
        'Flying', nan, nan, nan, 'Dragon', nan, 'Fairy', 'Fairy', nan, nan,
        'Flying', 'Flying', 'Flying', nan, nan, nan, 'Flying', 'Ground',
        'Ground', nan, nan, 'Flying', 'Psychic', nan, nan, nan, 'Psychic',
        nan, 'Steel', nan, 'Flying', 'Ground', 'Ground', nan, nan,
        'Poison', 'Steel', 'Steel', 'Rock', 'Fighting', 'Fighting', 'Ice',
        nan, nan, nan, 'Rock', 'Ground', 'Ground', 'Rock', nan, nan,
        'Flying', 'Flying', 'Flying', 'Fire', 'Fire', 'Fire', 'Dragon',
        nan, nan, nan, nan, nan, nan, nan, 'Psychic', nan, nan, nan, nan,
        nan, nan, nan, 'Ground', 'Ground', 'Dark', 'Dark', 'Flying',
        'Flying', 'Grass', nan, nan, nan, 'Dragon', nan, 'Fighting',
        'Fighting', 'Fighting', nan, 'Ground', 'Ground', 'Ground', nan,
        nan, nan, nan, nan, nan, 'Flying', nan, 'Poison', 'Grass', 'Grass',
        'Grass', nan, 'Dark', 'Dark', 'Flying', 'Flying', 'Flying',
        'Flying', 'Fairy', 'Fairy', 'Fairy', 'Fairy', 'Water', 'Flying',
        nan, 'Fighting', nan, nan, nan, 'Ground', 'Flying', 'Ghost', nan,
        nan, nan, nan, nan, 'Fairy', nan, nan, nan, 'Ghost', 'Ghost',
        'Fairy', 'Fairy', 'Rock', 'Rock', 'Rock', nan, 'Psychic',
        'Psychic', 'Psychic', nan, nan, nan, nan, nan, nan, nan, 'Poison',
        nan, nan, 'Dark', 'Dark', 'Dark', nan, nan, 'Ground', 'Ground',
        'Ground', nan, nan, nan, nan, nan, 'Dragon', 'Dragon', nan, 'Dark',
        'Flying', 'Flying', 'Fairy', nan, nan, 'Psychic', 'Psychic',
        'Ground', 'Ground', nan, 'Dark', 'Psychic', 'Psychic', 'Grass',
        'Grass', 'Bug', 'Bug', nan, nan, nan, nan, nan, nan, nan, nan, nan,
        'Flying', nan, nan, nan, nan, nan, nan, nan, 'Water', 'Water',
        'Water', nan, nan, nan, 'Rock', nan, nan, nan, 'Flying', 'Flying',
        'Psychic', 'Psychic', 'Psychic', 'Psychic', nan, nan, nan,
        'Psychic', 'Psychic', 'Psychic', 'Psychic', nan, nan, nan, 'Fire',
        'Flying', 'Flying', 'Psychic', nan, nan, nan, nan, nan, nan,
        'Ground', nan, 'Fighting', 'Fighting', nan, nan, 'Steel', 'Flying',
        'Flying', 'Flying', nan, 'Water', nan, nan, nan, nan, nan,
        'Poison', 'Poison', nan, nan, 'Steel', 'Steel', nan, 'Grass',
        'Ground', 'Steel', 'Flying', 'Flying', 'Flying', nan, nan, nan,
        nan, nan, nan, 'Ground', nan, 'Flying', 'Flying', nan, nan,
        'Fighting', nan, 'Flying', nan, nan, nan, 'Dark', 'Dark',
        'Psychic', 'Psychic', nan, 'Fairy', nan, 'Flying', 'Dark',
        'Ground', 'Ground', 'Ground', 'Ground', nan, nan, 'Steel', 'Steel',
        nan, nan, 'Bug', 'Dark', 'Fighting', 'Fighting', nan, nan, nan,
        'Flying', 'Ice', 'Ice', 'Ice', 'Ice', 'Steel', nan, 'Rock', nan,
        nan, nan, 'Flying', 'Flying', nan, nan, 'Flying', 'Ground', nan,
        'Fighting', 'Fighting', 'Steel', nan, 'Ghost', 'Ghost', 'Fire',
        'Water', 'Ice', 'Flying', 'Grass', nan, nan, nan, 'Dragon',
        'Dragon', 'Steel', nan, 'Dragon', 'Dragon', nan, nan, nan, nan,
        nan, 'Flying', nan, 'Fire', nan, nan, nan, nan, 'Fighting',
        'Fighting', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, 'Flying', 'Flying', 'Flying',
        nan, nan, nan, nan, nan, 'Flying', 'Flying', nan, 'Steel', nan,
        'Fairy', nan, nan, nan, nan, 'Ground', 'Ground', nan, nan, 'Grass',
        'Grass', 'Grass', 'Poison', 'Poison', 'Poison', 'Fairy', 'Fairy',
        nan, nan, nan, 'Dark', 'Dark', 'Dark', nan, nan, 'Psychic', nan,
        'Rock', 'Rock', 'Fighting', 'Fighting', 'Flying', nan, nan, 'Rock',
        'Rock', 'Flying', 'Flying', nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, 'Flying', 'Flying', nan, nan, nan, 'Grass',
        'Grass', 'Flying', nan, 'Steel', 'Poison', 'Poison', 'Ghost',
        'Ghost', nan, 'Electric', 'Electric', 'Steel', 'Steel', nan, nan,
        nan, nan, nan, nan, nan, nan, 'Fire', 'Fire', 'Fire', nan, nan,
        nan, nan, nan, nan, nan, nan, 'Electric', nan, nan, nan, 'Ghost',
        'Ghost', 'Steel', 'Steel', nan, 'Flying', 'Flying', 'Flying',
        'Flying', nan, 'Steel', 'Dragon', 'Dragon', 'Dragon', 'Fire',
        'Fire', 'Fighting', 'Fighting', 'Fighting', nan, nan, 'Flying',
        'Flying', 'Fire', 'Electric', 'Flying', 'Flying', 'Ice', 'Ice',
        'Ice', 'Fighting', 'Fighting', 'Psychic', 'Fighting', 'Steel', nan,
        nan, 'Fighting', nan, nan, 'Psychic', nan, nan, 'Dark', nan,
        'Ground', 'Flying', 'Flying', 'Flying', nan, nan, 'Flying',
        'Normal', 'Normal', nan, nan, nan, nan, nan, nan, 'Dark', nan, nan,
        nan, nan, 'Ghost', 'Ghost', 'Ghost', 'Ghost', nan, nan, nan, nan,
        'Psychic', 'Psychic', 'Water', 'Water', 'Water', 'Dragon', nan,
        nan, 'Normal', 'Normal', 'Dragon', 'Dragon', 'Ice', 'Ice', nan,
        'Flying', 'Fairy', 'Fairy', nan, nan, nan, 'Fairy', 'Grass',
        'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass',
        'Grass', 'Grass', nan, nan, 'Dragon', 'Dragon', nan, 'Flying',
        'Ground', 'Fairy', 'Fairy', 'Ghost', 'Dark', 'Water'], dtype=object))

In [9]:
values_Type1_Type2 = Pokemon[['Type 1', 'Type 2']].values
values_Type1_Type2

array([['Grass', 'Poison'],
       ['Grass', 'Poison'],
       ['Grass', 'Poison'],
       ...,
       ['Psychic', 'Ghost'],
       ['Psychic', 'Dark'],
       ['Fire', 'Water']], dtype=object)

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [12]:
# your code here
Pokemon['Name'] = Pokemon['Name'].str.replace(r'.*Mega', 'Mega', regex=True)
print(Pokemon['Name'].head(10))

0           Bulbasaur
1             Ivysaur
2            Venusaur
3       Mega Venusaur
4          Charmander
5          Charmeleon
6           Charizard
7    Mega Charizard X
8    Mega Charizard Y
9            Squirtle
Name: Name, dtype: object

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [14]:
# your code here
Pokemon['A/D Ratio'] = Pokemon['Attack'] / Pokemon['Defense']
Pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,1.103448
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,1.076923
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1.171171
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1.333333
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,0.738462

#### Identify the pokemon with the highest `A/D Ratio`.

In [17]:
# your code here
highestADRatio_count_value = Pokemon['A/D Ratio'].value_counts().idxmax("name")
print("Value in 'x' with the highest count in 'y':", highestADRatio_count_value)

TypeError: '>=' not supported between instances of 'str' and 'int'

In [19]:
highest_ratio_Pokemon = Pokemon.loc[Pokemon['A/D Ratio'].idxmax(), 'Name']
highest_ratio_Pokemon

'DeoxysAttack Forme'

#### Identify the pokemon with the lowest A/D Ratio.

In [20]:
# your code here
lowest_ratio_Pokemon = Pokemon.loc[Pokemon['A/D Ratio'].idxmin(), 'Name']
lowest_ratio_Pokemon

'Shuckle'

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [22]:
# your code here
Pokemon['Combo Type'] = Pokemon['Type 1']
Pokemon['Combo Type'] = Pokemon['Combo Type'].fillna('') + Pokemon['Type 2'].fillna('')
Pokemon.loc[Pokemon['Type 2'].notna(), 'Combo Type'] = Pokemon['Combo Type'].str.replace(r'^([^ ]+)$', r'\1-', regex=True)
Pokemon['Combo Type'] = Pokemon['Combo Type'].str.rstrip('-')
Pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,GrassPoison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,GrassPoison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,GrassPoison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,GrassPoison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302,Fire
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,1.103448,Fire
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,1.076923,FireFlying
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1.171171,FireDragon
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1.333333,FireFlying
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,0.738462,Water

In [25]:
combo_type_col = Pokemon.pop('Combo Type')
Pokemon.pop.insert(Pokemon.columns.get_loc('Type 2') + 1, 'Combo Type', combo_type_col)
Pokemon.head(10)

KeyError: 'Combo Type'

In [26]:
combo_type_col = Pokemon.pop('Combo Type')
Pokemon.insert(Pokemon.columns.get_loc('Type 2') + 1, 'Combo Type', combo_type_col)
Pokemon.head(10)

KeyError: 'Combo Type'

,#,Name,Type 1,Type 2,Combo Type,Combo Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,NaN,NaN,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,NaN,NaN,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,NaN,NaN,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,NaN,NaN,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,NaN,NaN,NaN,309,39,52,43,60,50,65,1,False,1.209302
5,5,Charmeleon,Fire,NaN,NaN,NaN,405,58,64,58,80,65,80,1,False,1.103448
6,6,Charizard,Fire,Flying,NaN,NaN,534,78,84,78,109,85,100,1,False,1.076923
7,6,Mega Charizard X,Fire,Dragon,NaN,NaN,634,78,130,111,130,85,100,1,False,1.171171
8,6,Mega Charizard Y,Fire,Flying,NaN,NaN,634,78,104,78,159,115,100,1,False,1.333333
9,7,Squirtle,Water,NaN,NaN,NaN,314,44,48,65,50,64,43,1,False,0.738462

In [35]:
columns_to_delete = ['Combo Type', 'Combo Type']
Pokemon = Pokemon.drop(columns=columns_to_del)

NameError: name 'columns_to_del' is not defined

In [36]:
Pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,1.103448
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,1.076923
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1.171171
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1.333333
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,0.738462

In [37]:
Pokemon['Combo Type'] = Pokemon['Type 1']
Pokemon['Combo Type'] = Pokemon['Combo Type'].fillna('') + Pokemon['Type 2'].fillna('')
Pokemon.loc[Pokemon['Type 2'].notna(), 'Combo Type'] = Pokemon['Combo Type'].str.replace(r'^([^ ]+)$', r'\1-', regex=True)
Pokemon['Combo Type'] = Pokemon['Combo Type'].str.rstrip('-')
Pokemon.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,GrassPoison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,GrassPoison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,GrassPoison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,GrassPoison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302,Fire

In [ ]:
columns = Pokemon.columns.tolist()
type2_index = columns.index('Type 2')
columns.insert(type2_index + 1, 'Combo Type')
Pokemon = Pokemon.reindex(columns=columns)

In [ ]:
defense_index = columns.index('Defense')
columns.insert(defense_index + 1, 'A/D Ratio')
Pokemon = Pokemon.reindex(columns=columns)

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [40]:
# your code here
top5_ADratio = Pokemon.nlargest(5, 'A/D Ratio')['Name'].tolist()
top5_ADratio

['DeoxysAttack Forme', 'Carvanha', 'Mega Beedrill', 'Cranidos', 'Sharpedo']

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [41]:
# your code here
aggregated_combo_types = Pokemon[Pokemon['Name'].isin(top5_ADratio)]['Combo Type'].unique().tolist()
aggregated_combo_types

['BugPoison', 'WaterDark', 'Psychic', 'Rock']

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [11]:
# your code here

In [44]:
new_Pokemon = Pokemon.set_index('Combo Type')
new_Pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Combo Type,,,,,,,,,,,,,,
GrassPoison,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
GrassPoison,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
GrassPoison,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
GrassPoison,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
Fire,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RockFairy,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667
RockFairy,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545
PsychicGhost,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333
PsychicDark,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667
FireWater,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667